stages:
  - test
  - clean
  - build
  - deploy

tests:
  stage: test
  only:
    - master
  tags:
    - appditto_mac
  script:
    - python3 -B -m py_compile server/api.py
  interruptible: true

clean:
  stage: clean
  only:
    - master
  tags:
    - appditto_mac
  script:
    - rm -rf node_modules
    - npm install
  interruptible: true

nuxt:build:
  stage: build
  only:
    - master
  tags:
    - appditto_mac
  script:
    - npm run build
  interruptible: true

deploy_nuxt:
  stage: deploy
  only:
    - master
  tags:
    - appditto_mac
  script:
    - ssh -oStrictHostKeyChecking=no $SSH_USER@$SSH_HOST "cd ${APP_DIRECTORY}; git add .; git reset --hard; git pull origin master"
    - ssh -oStrictHostKeyChecking=no $SSH_USER@$SSH_HOST "cd ${APP_DIRECTORY}; npm run build"
    - ssh -oStrictHostKeyChecking=no $SSH_USER@$SSH_HOST "cd ${APP_DIRECTORY}; sudo systemctl restart ${APP_SERVICE_NAME}"

deploy_python:
  stage: deploy
  only:
    - master
  tags:
    - appditto_mac
  script:
    - ssh -oStrictHostKeyChecking=no $SSH_USER@$SSH_HOST "cd ${APP_DIRECTORY}; git add .; git reset --hard; git pull origin master"
    - ssh -oStrictHostKeyChecking=no $SSH_USER@$SSH_HOST "cd ${APP_DIRECTORY}; sudo systemctl restart ${SERVER_SERVICE_NAME}"