apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: apddito-com-ingress
  namespace: appditto-com
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/configuration-snippet: |
        real_ip_header CF-Connecting-IP;
spec:
  tls:
  - hosts:
    - appditto.com
    secretName: appditto-com-server-secret
  rules:
  - host: natricon-go-server.appditto.com
    http:
      paths:
      - path: /
        backend:
          serviceName: nuxt-appditto-service
          servicePort: 3000
      - path: /inquire
        backend:
          serviceName: apddito-backend-service
          servicePort: 3001